# Generated by Django 5.2 on 2026-02-18 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('slug', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('slug', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(blank=True, help_text='A short title, max 200 characters', max_length=200, null=True)),
                ('post_body', models.CharField(help_text='The body of the post', max_length=1000)),
                ('pub_date', models.DateField(help_text='The date of the publication', verbose_name='date published')),
                ('slug', models.CharField(blank=True, help_text='A short slug', max_length=100, null=True)),
                ('featured_image', models.ImageField(blank=True, help_text='Path to the featured image', null=True, upload_to='featured_images/')),
                ('excerpt', models.CharField(blank=True, help_text='The content of the body in a short form', max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], help_text='The status of the post. Can be: draft,published or archived', null=True)),
                ('author', models.ForeignKey(help_text='The author of the post, Foreign key', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='The category of the post, 1 can be used maximum to 1 post, Foreign key', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.category')),
                ('tags', models.ManyToManyField(blank=True, help_text='The tags of the post, multiple can be used for a post, ManyToManyField', to='blogs.tag')),
            ],
        ),
    ]
