# Generated by Django 5.2 on 2026-08-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, help_text='A short summary of the post', null=True),
        ),
    ]
