# Generated by Django 5.2 on 2026-08-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_post_body_post_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Path to the featured image', null=True, upload_to='blog/static/blog/images/'),
        ),
    ]
