# Generated by Django 5.2 on 2026-08-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.CharField(blank=True, help_text='The featured image of the post', max_length=200, null=True),
        ),
    ]
